spring:
  application:
    name: quickticket
  datasource:
    master:
      driver-class-name: com.mysql.cj.jdbc.Driver
    replica:
      driver-class-name: com.mysql.cj.jdbc.Driver
  cache:
    type: redis
  jakson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: Asia/Seoul
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 200